#define NPMTMAX 6
#define NTIMEMAX 50000
#define NSLOTMAX 2000
#define MAXFADC 4096
int NPMT, NPMT_UP, NTIME, TIMESLOT, NSLOT;
double TIMEUNIT;
double TANK_RADIUS,TANK_HEIGHT,TankTopArea,TankSideArea, TANK_ZSPLIT;
double X_PMT[NPMTMAX],Y_PMT[NPMTMAX],Z_PMT[NPMTMAX],RAD_PMT[NPMTMAX];

#define CHERENKOV_CONSTANT .0458506
#define NWAVELENGTH 30
#define WAVELENGTH_MIN 305e-9
#define DWAVELENGTH 10e-9
double CHERENKOV_PROBABILITY[NWAVELENGTH];
double WATER_ABSORPTION_LENGTH[NWAVELENGTH];
double LINER_REFLECTIVITY[NWAVELENGTH];
double PMT_QUANTUM_EFFICIENCY[NWAVELENGTH];
double CHERENKOV_FACTOR;
double WATER_ABSORPTION_LENGTH_MAX;
double ADD_ABSORPTION_LENGTH;
double REFLECTIVITY_FACTOR[3]; // 0,1,2 for top, side, bottom
double COLLECTION_EFFICIENCY;
double SPECULAR_FRACTION;
double FADC_PER_PE,SIGMA_PER_PE,SIGMA_BASE,DYNODE_ANODE_RATIO;
